AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BaseName:
    Type: String
  VpcCidrBlock:
    Type: String
  SubnetCidrBlock:
    Type: String
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
  ImageId:
    Type: String
  EbsVolumeSize:
    Type: String
Resources:
# ---------------- Network ---------------- #
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: 
        - Key: Name
          Value: !Ref BaseName
  Subnet: 
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetCidrBlock
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub ${BaseName}-subnet
  InternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub ${BaseName}-igw
  InternetGatewayAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  RouteTable: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub ${BaseName}-route
  Route: 
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId: !Ref RouteTable 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable
# ---------------- EC2 ---------------- #
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: InternetGatewayAttachment
    Properties:
      Path: /
      Roles:
      - Ref: InstanceIAMRole
  InstanceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${BaseName}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
      - Key: Name
        Value: !Ref BaseName
      KeyName: !Ref KeyPairName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      SubnetId: !Ref Subnet
      SecurityGroupIds:
      - !Ref SecurityGroupEc2
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdh"
        Ebs:
          VolumeType: "gp2"
          DeleteOnTermination: true
          VolumeSize: !Ref EbsVolumeSize
  SecurityGroupEc2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Block all public access"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${BaseName}-sg
  CiSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BaseName}-src
      VersioningConfiguration:
        Status: Enabled
  CiTempBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BaseName}-temp
      VersioningConfiguration:
        Status: Enabled
  CiOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BaseName}-output
      VersioningConfiguration:
        Status: Enabled